# PULSE codegen example: BulkBackfill — date-range historical replay from
# a JDBC source into bronze.
#
# Distinct from SnapshotIngestion (full-table dump on a recurring schedule):
#   - BulkBackfill is one-shot or rare: replay history because we just
#     added a pipeline OR fixed an upstream defect and need to rehydrate.
#   - Strictly bounded by [BACKFILL_START, BACKFILL_END]; never leaves
#     the window open-ended. Both inputs accept either ISO date literals
#     or PULSE date mnemonics (BOM-12, EOM-1, PBD, etc.) — the resolver
#     handles both, so the same call site supports fixed and dynamic.
#   - Idempotent: re-running the same window cleanly overwrites with no
#     duplicates. Achieved via Delta replaceWhere on the chunk's date range
#     (or the format's equivalent for Iceberg / Parquet).
#   - Chunked by month to bound JDBC partition memory; tune __CHUNK_DAYS__
#     for source row density.
#
# Convention notes:
#   - __PLACEHOLDER__ tokens are substituted by CodeGenerationService at
#     codegen time. They are NOT env vars.
#   - Storage placeholders (#30) come from StoragePlaceholderResolver:
#       __TABLE_PATH__         object-store URI when format is path-based
#                              (delta | iceberg_external | iceberg_bq_managed | parquet)
#       __BQ_TABLE__           project.dataset.table for bq_native
#       __LAKE_FORMAT__        chosen format; drives the write branch below
#       __STORAGE_BACKEND__    'DPC' | 'GCP'
#   - Date inputs (BACKFILL_START_INPUT, BACKFILL_END_INPUT) are
#     RESOLVED AT RUNTIME by pulse_dates so a DAG run on 2026-05-15 vs
#     2027-05-15 produces the right window without regenerating code.
#   - PULSE_* env vars are runtime-only (Airflow per-run templates).
#   - Secrets resolve from the secret manager via gcp-sm:// references
#     surfaced as env vars by the Airflow connection layer; never literals.
#
# Generated by PULSE codegen against the BulkBackfill blueprint. The agent
# SHOULD pattern its proposed params and DAG wiring on this file.

from datetime import date, timedelta
import logging
import os

from pyspark.sql import DataFrame, SparkSession
from pyspark.sql import functions as F
from pyspark.sql.types import StringType

# pulse_dates is the platform-installed mnemonic resolver. Pure-calendar
# mnemonics compute in-process; business-day mnemonics (PBD/NBD/FBOM/LBOM/
# NBDOM) query date_dim_holiday_calendar against the tenant's holiday
# calendar. ISO date literals pass through unchanged.
from pulse_dates import resolve_mnemonic

# pulse_pipeline_state is the platform-installed high-water-mark helper.
# Always import from the platform; never roll your own.
from pulse_pipeline_state import advance_high_water_mark


# ---------------------------------------------------------------------
# Runtime-only — Airflow per-execution values.
# ---------------------------------------------------------------------
RUN_ID = os.environ["PULSE_RUN_ID"]
PULSE_BUSINESS_DATE = os.environ.get("PULSE_BUSINESS_DATE", date.today().isoformat())
PULSE_PROCESSING_TS = os.environ.get("PULSE_PROCESSING_TS", "{{ ts }}")
AS_OF_DATE = date.fromisoformat(PULSE_BUSINESS_DATE)


# ---------------------------------------------------------------------
# Static config — substituted at codegen time from blueprint params.
# ---------------------------------------------------------------------
PIPELINE_NAME = "__PIPELINE_NAME__"
PIPELINE_SLUG = "__PIPELINE_SLUG__"
TENANT_SLUG = "__TENANT_SLUG__"
DOMAIN_SLUG = "__DOMAIN_SLUG__"
SOR_SLUG = "__SOR_SLUG__"
TABLE_SLUG = "__TABLE_SLUG__"

# Storage convention — resolved by StoragePlaceholderResolver against
# the SubPipelineInstance's storage_backend, lake_layer, lake_format.
# Bronze layer for BulkBackfill; bq_native is illegal at bronze (it's
# gold-only) so __BQ_TABLE__ will be empty here unless the future
# allows it.
LAKE_FORMAT = "__LAKE_FORMAT__"        # 'delta' | 'iceberg_external' | 'iceberg_bq_managed' | 'parquet'
STORAGE_BACKEND = "__STORAGE_BACKEND__"  # 'DPC' | 'GCP'
TABLE_PATH = "__TABLE_PATH__"          # 's3a://.../bronze/<table>/' or 'gs://.../bronze/<table>/'
BQ_TABLE = "__BQ_TABLE__"              # populated only when LAKE_FORMAT='bq_native' (gold-only; empty here)

# Date inputs accept mnemonics OR ISO literals. Codegen substitutes whatever
# the user picked in the configure dialog. Examples:
#   "BOM-12" → "12 months ago, beginning of month"
#   "EOM-1"  → "end of last month"
#   "PBD"    → "previous business day" (calendar-aware)
#   "2024-01-01" → fixed historical date
BACKFILL_START_INPUT = "__BACKFILL_START_INPUT__"
BACKFILL_END_INPUT = "__BACKFILL_END_INPUT__"
HOLIDAY_CALENDAR_ID = "__HOLIDAY_CALENDAR_ID__"   # 'US-FED' | 'US-NYSE'
FISCAL_OFFSET_MONTHS = __FISCAL_OFFSET_MONTHS__   # int from domain.business_date_config

CHUNK_DAYS = __CHUNK_DAYS__

JDBC_URL = "__SOURCE_JDBC_URL__"
JDBC_DRIVER = "__SOURCE_JDBC_DRIVER__"            # e.g., oracle.jdbc.OracleDriver
JDBC_TABLE = "__SOURCE_JDBC_TABLE__"              # SCHEMA.TABLE
DATE_COLUMN = "__SOURCE_DATE_COLUMN__"            # column we partition the read by
PRIMARY_KEY = "__SOURCE_PRIMARY_KEY__"            # JDBC partitionColumn
JDBC_NUM_PARTITIONS = __JDBC_NUM_PARTITIONS__


# ---------------------------------------------------------------------
# Resolve date inputs against the tenant's holiday calendar.
# ---------------------------------------------------------------------
BACKFILL_START = resolve_mnemonic(
    BACKFILL_START_INPUT, as_of=AS_OF_DATE,
    calendar_id=HOLIDAY_CALENDAR_ID,
    fiscal_offset_months=FISCAL_OFFSET_MONTHS,
)
BACKFILL_END = resolve_mnemonic(
    BACKFILL_END_INPUT, as_of=AS_OF_DATE,
    calendar_id=HOLIDAY_CALENDAR_ID,
    fiscal_offset_months=FISCAL_OFFSET_MONTHS,
)


# ---------------------------------------------------------------------
# Secrets — resolved from the secret manager (gcp-sm://) at runtime by
# the Airflow connection layer and exposed as env vars to this job.
# Plaintext credentials in generated code are FORBIDDEN.
# ---------------------------------------------------------------------
JDBC_USER = os.environ["__SOURCE_NAME___USERNAME"]
JDBC_PASSWORD = os.environ["__SOURCE_NAME___PASSWORD"]


log = logging.getLogger("pulse.bulk_backfill")
log.setLevel(logging.INFO)


def plan_chunks(start, end, chunk_days):
    """Split [start, end] inclusive into chunks of chunk_days days.

    Each chunk is the unit of idempotent overwrite — if the job dies mid-chunk,
    re-running the same window overwrites only that chunk.
    """
    if start > end:
        raise ValueError(f"backfill_start_date {start} is after backfill_end_date {end}")
    chunks = []
    cursor = start
    while cursor <= end:
        chunk_end = min(cursor + timedelta(days=chunk_days - 1), end)
        chunks.append((cursor, chunk_end))
        cursor = chunk_end + timedelta(days=1)
    return chunks


def read_chunk(spark, chunk_start, chunk_end):
    """Read one chunk via JDBC.

    partitionColumn / lowerBound / upperBound / numPartitions force Spark to
    issue parallel JDBC reads; without them a multi-million-row chunk pins
    one executor for hours. The predicate is wrapped in a subquery so it
    pushes down to the database (avoiding re-issuing the same query for
    every partition).
    """
    predicate = (
        f"{DATE_COLUMN} >= DATE '{chunk_start.isoformat()}' "
        f"AND {DATE_COLUMN} <= DATE '{chunk_end.isoformat()}'"
    )
    log.info("reading chunk start=%s end=%s table=%s partitions=%d",
             chunk_start, chunk_end, JDBC_TABLE, JDBC_NUM_PARTITIONS)
    return (
        spark.read.format("jdbc")
        .option("url", JDBC_URL)
        .option("driver", JDBC_DRIVER)
        .option("user", JDBC_USER)
        .option("password", JDBC_PASSWORD)
        .option("dbtable", f"(SELECT * FROM {JDBC_TABLE} WHERE {predicate}) src")
        .option("partitionColumn", PRIMARY_KEY)
        .option("lowerBound", "0")
        .option("upperBound", str(2**31 - 1))
        .option("numPartitions", JDBC_NUM_PARTITIONS)
        .option("fetchsize", "10000")
        .load()
    )


def audit(df, chunk_start):
    """Add PULSE audit columns. Bronze MUST NOT transform — only audit
    columns are added. Any cleaning or casting belongs in the silver
    layer (BronzeToSilverCleaning)."""
    return (
        df
        .withColumn("ds", F.date_format(F.col(DATE_COLUMN), "yyyy-MM-dd"))
        .withColumn("_pulse_business_date", F.lit(chunk_start.isoformat()).cast(StringType()))
        .withColumn("_pulse_processing_ts", F.lit(PULSE_PROCESSING_TS))
        .withColumn("_pulse_run_id", F.lit(RUN_ID))
        .withColumn("_pulse_pipeline", F.lit(PIPELINE_NAME))
        .withColumn("_pulse_source", F.lit(f"{SOR_SLUG}/{JDBC_TABLE}"))
    )


def write_chunk(df, chunk_start, chunk_end):
    """Write one chunk to bronze with format-aware idempotency.

    Each format has its own idempotency primitive:
      - delta              → replaceWhere on the chunk's ds range
      - iceberg_external   → MERGE/overwrite_partitions semantics
      - iceberg_bq_managed → BQ-managed Iceberg via spark-bigquery-connector
      - parquet            → overwrite the matched ds partitions
    bq_native is gold-only (locked rule) and won't appear here.
    """
    audited = audit(df, chunk_start)
    replace_where = (
        f"ds >= '{chunk_start.isoformat()}' AND ds <= '{chunk_end.isoformat()}'"
    )

    written = audited.cache()
    row_count = written.count()
    log.info("writing chunk start=%s end=%s rows=%d format=%s",
             chunk_start, chunk_end, row_count, LAKE_FORMAT)

    if LAKE_FORMAT == "delta":
        # replaceWhere is THE idempotency primitive for chunked backfills:
        # overwrites only the partitions covered by the predicate, leaving
        # prior chunks (and any rows outside the window) untouched.
        (
            written.write
            .format("delta")
            .mode("overwrite")
            .option("replaceWhere", replace_where)
            .partitionBy("ds")
            .save(TABLE_PATH)
        )
    elif LAKE_FORMAT == "iceberg_external":
        # Iceberg's overwritePartitions rewrites only the matched ds
        # partitions. Requires the destination table to already exist
        # (PR-reviewed DDL artifact); this job assumes existence.
        written.createOrReplaceTempView("pulse_chunk")
        # Use SQL because the Spark Iceberg DataFrame API does not yet
        # expose overwritePartitions cleanly across all engines.
        written.sparkSession.sql(
            f"DELETE FROM iceberg.`{TABLE_PATH}` WHERE {replace_where}"
        )
        written.writeTo(f"iceberg.`{TABLE_PATH}`").append()
    elif LAKE_FORMAT == "iceberg_bq_managed":
        # BQ-managed Iceberg goes through the spark-bigquery-connector;
        # the connector accepts the table as a path under the connector's
        # configured BQ-managed-table mapping.
        (
            written.write
            .format("bigquery")
            .option("table", BQ_TABLE if BQ_TABLE else TABLE_PATH)
            .option("writeMethod", "indirect")
            .mode("append")
            .save()
        )
    elif LAKE_FORMAT == "parquet":
        # Plain parquet — no ACID metadata. Chunked overwrite is achieved
        # by writing each ds partition separately with mode='overwrite'
        # and dynamic-partition-overwrite enabled.
        (
            written.write
            .format("parquet")
            .mode("overwrite")
            .option("partitionOverwriteMode", "dynamic")
            .partitionBy("ds")
            .save(TABLE_PATH)
        )
    else:
        raise ValueError(
            f"Unsupported LAKE_FORMAT for BulkBackfill bronze: {LAKE_FORMAT}. "
            "Legal: delta | iceberg_external | iceberg_bq_managed | parquet."
        )

    written.unpersist()
    return row_count


def main():
    spark = (
        SparkSession.builder
        .appName(f"pulse-bulk-backfill-{PIPELINE_SLUG}-{RUN_ID}")
        .getOrCreate()
    )

    log.info(
        "BulkBackfill start. as_of=%s, window=[%s, %s] (resolved from inputs %r..%r), "
        "chunk_days=%d, calendar=%s, table=%s, backend=%s, format=%s",
        AS_OF_DATE, BACKFILL_START, BACKFILL_END,
        BACKFILL_START_INPUT, BACKFILL_END_INPUT,
        CHUNK_DAYS, HOLIDAY_CALENDAR_ID, JDBC_TABLE,
        STORAGE_BACKEND, LAKE_FORMAT,
    )
    chunks = plan_chunks(BACKFILL_START, BACKFILL_END, CHUNK_DAYS)
    log.info("planned %d chunks", len(chunks))

    total_rows = 0
    for chunk_start, chunk_end in chunks:
        df = read_chunk(spark, chunk_start, chunk_end)
        rows = write_chunk(df, chunk_start, chunk_end)
        total_rows += rows
        advance_high_water_mark(
            pipeline=PIPELINE_NAME,
            run_id=RUN_ID,
            high_water_mark=chunk_end.isoformat(),
            row_count=rows,
        )
        log.info("chunk done end=%s rows=%d cumulative=%d", chunk_end, rows, total_rows)

    log.info("BulkBackfill complete window=[%s, %s] total_rows=%d",
             BACKFILL_START, BACKFILL_END, total_rows)
    spark.stop()


if __name__ == "__main__":
    main()
