apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: pulse-frontend
  labels:
    app: pulse-frontend
spec:
  runPolicy: SerialLatestOnly
  completionDeadlineSeconds: 2400
  source:
    type: Git
    git:
      uri: https://github.com/naghegde13/pulse-test.git
      ref: main
    contextDir: frontend
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: DockerImage
        name: registry.access.redhat.com/ubi9/nodejs-22:latest
      env:
        - name: NEXT_PUBLIC_API_URL
          value: https://pulse-backend-naghegde13-dev.apps.rm3.7wse.p1.openshiftapps.com
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "2"
      memory: "2Gi"
  output:
    to:
      kind: ImageStreamTag
      name: pulse-frontend:latest
  triggers:
    - type: ConfigChange
    - type: ImageChange
