apiVersion: v1
kind: ConfigMap
metadata:
  name: pulse-frontend-config
  labels:
    app: pulse-frontend
data:
  PORT: "3000"
  NEXT_PUBLIC_API_URL: "https://pulse-backend-naghegde13-dev.apps.rm3.7wse.p1.openshiftapps.com"
