-- ARCH-008 phase 5: closed broker invocation blueprint for composition design.

INSERT INTO blueprints (
    id, blueprint_key, name, description, category, version,
    params_schema, input_ports, output_ports, runtime_requirements,
    deferred, subcategory, artifact_types, compute_backend,
    composition_role, valid_layers, usage_guidance, required_params_schema,
    optional_params_schema, ui_schema, emit_strategy, supports_reuse,
    schema_behavior, codegen_hints, status, pipeline_config, add_surface
) VALUES (
    '01JBP0BROKER0REMOTEINV001',
    'RemotePipelineInvocation',
    'Remote Pipeline Invocation',
    'Invokes an exposed remote Airflow DAG through a validated peer target mirror and runtime-owned Airflow connection.',
    'ORCHESTRATION',
    '1.0.0',
    '[
      {"name":"federated_tenant_key","type":"string","required":true},
      {"name":"remote_target_ref","type":"string","required":true},
      {"name":"environment","type":"string","required":true},
      {"name":"airflow_connection_id","type":"string","required":true},
      {"name":"remote_dag_id","type":"string","required":false},
      {"name":"poll_interval_seconds","type":"integer","required":false},
      {"name":"timeout_seconds","type":"integer","required":false},
      {"name":"payload_template","type":"object","required":false}
    ]'::jsonb,
    '[{"name":"trigger","description":"Upstream trigger dependency"}]'::jsonb,
    '[{"name":"remote_completion","description":"Remote pipeline completion facts"}]'::jsonb,
    '{"requiresBrokerTrust":true,"requiresRuntimeProjection":true,"requiresAirflowConnection":true,"runtimePulseApiRequired":false}'::jsonb,
    false,
    'broker',
    '["BROKER_OPERATOR","BROKER_INVOCATION_MANIFEST"]'::jsonb,
    'AIRFLOW',
    'orchestration',
    '[]'::jsonb,
    '{"addGuidance":"Use only for trusted peer Airflow targets that have a current runtime mirror, projection, and Airflow connection in the executing environment."}'::jsonb,
    '{"federated_tenant_key":{"type":"string"},"remote_target_ref":{"type":"string"},"environment":{"type":"string"},"airflow_connection_id":{"type":"string"}}'::jsonb,
    '{"remote_dag_id":{"type":"string"},"poll_interval_seconds":{"type":"integer"},"timeout_seconds":{"type":"integer"},"payload_template":{"type":"object"}}'::jsonb,
    '{"panel":"broker","fields":["federated_tenant_key","remote_target_ref","environment","airflow_connection_id","remote_dag_id","poll_interval_seconds","timeout_seconds","payload_template"]}'::jsonb,
    'broker_invocation',
    false,
    '{"emitsTable":false,"requiresSchemaPropagation":false}'::jsonb,
    '{"emitter":"broker_remote_invocation","projectionKey":"brokerInvocations"}'::jsonb,
    'active',
    false,
    'composition'
) ON CONFLICT (blueprint_key) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    params_schema = EXCLUDED.params_schema,
    runtime_requirements = EXCLUDED.runtime_requirements,
    subcategory = EXCLUDED.subcategory,
    artifact_types = EXCLUDED.artifact_types,
    compute_backend = EXCLUDED.compute_backend,
    composition_role = EXCLUDED.composition_role,
    usage_guidance = EXCLUDED.usage_guidance,
    required_params_schema = EXCLUDED.required_params_schema,
    optional_params_schema = EXCLUDED.optional_params_schema,
    ui_schema = EXCLUDED.ui_schema,
    emit_strategy = EXCLUDED.emit_strategy,
    schema_behavior = EXCLUDED.schema_behavior,
    codegen_hints = EXCLUDED.codegen_hints,
    status = EXCLUDED.status,
    pipeline_config = EXCLUDED.pipeline_config,
    add_surface = EXCLUDED.add_surface,
    updated_at = NOW();
