-- Gate 4 sensing/orchestration rollout foundation
-- Adds first-class sensing blueprints with explicit metadata so sensors are
-- modeled as orchestration instances rather than inferred only from datasets.

INSERT INTO blueprints (
    id,
    blueprint_key,
    name,
    description,
    category,
    version,
    params_schema,
    input_ports,
    output_ports,
    deferred,
    pipeline_config,
    subcategory,
    artifact_types,
    compute_backend,
    composition_role,
    valid_layers,
    usage_guidance,
    required_params_schema,
    optional_params_schema,
    ui_schema,
    emit_strategy,
    supports_reuse,
    schema_behavior,
    codegen_hints,
    status
) VALUES
(
    '01JBP0ORCH0FILESENSOR001',
    'FileArrivalSensor',
    'File Arrival Sensor',
    'Waits for a file path or prefix to become available before continuing the pipeline.',
    'ORCHESTRATION',
    '1.0.0',
    '[{"name":"storage_kind","type":"enum","options":["s3","sftp"],"required":true},{"name":"path","type":"string","required":true},{"name":"poke_interval_seconds","type":"integer","default":300},{"name":"timeout_seconds","type":"integer","default":3600},{"name":"mode","type":"enum","options":["poke","reschedule"],"default":"reschedule"}]'::jsonb,
    '[]'::jsonb,
    '[{"name":"ready_signal","description":"Proceed when file arrival is confirmed"}]'::jsonb,
    false,
    false,
    'sensing',
    '["airflow_sensor"]'::jsonb,
    'airflow',
    'orchestration_sensor',
    '["bronze","silver","gold"]'::jsonb,
    '{"phase":"gate4","purpose":"explicit_sensing"}'::jsonb,
    '{"storage_kind":{"type":"enum","required":true},"path":{"type":"string","required":true}}'::jsonb,
    '{"poke_interval_seconds":{"type":"integer"},"timeout_seconds":{"type":"integer"},"mode":{"type":"enum"}}'::jsonb,
    '{"editor":"sensor"}'::jsonb,
    'runtime_only',
    false,
    '{"effect_type":"readiness_gate","conflict_policy":"block"}'::jsonb,
    '{"airflow_operator":"file_or_object_sensor"}'::jsonb,
    'active'
),
(
    '01JBP0ORCH0OBJSENSOR0001',
    'ObjectStoreKeySensor',
    'Object Store Key Sensor',
    'Waits for an object-store key or prefix to become available before continuing the pipeline.',
    'ORCHESTRATION',
    '1.0.0',
    '[{"name":"bucket","type":"string","required":true},{"name":"object_key","type":"string","required":true},{"name":"wildcard_match","type":"boolean","default":true},{"name":"poke_interval_seconds","type":"integer","default":300},{"name":"timeout_seconds","type":"integer","default":3600},{"name":"mode","type":"enum","options":["poke","reschedule"],"default":"reschedule"}]'::jsonb,
    '[]'::jsonb,
    '[{"name":"ready_signal","description":"Proceed when object-store readiness is confirmed"}]'::jsonb,
    false,
    false,
    'sensing',
    '["airflow_sensor"]'::jsonb,
    'airflow',
    'orchestration_sensor',
    '["bronze","silver","gold"]'::jsonb,
    '{"phase":"gate4","purpose":"explicit_sensing"}'::jsonb,
    '{"bucket":{"type":"string","required":true},"object_key":{"type":"string","required":true}}'::jsonb,
    '{"wildcard_match":{"type":"boolean"},"poke_interval_seconds":{"type":"integer"},"timeout_seconds":{"type":"integer"},"mode":{"type":"enum"}}'::jsonb,
    '{"editor":"sensor"}'::jsonb,
    'runtime_only',
    false,
    '{"effect_type":"readiness_gate","conflict_policy":"block"}'::jsonb,
    '{"airflow_operator":"s3_key_sensor"}'::jsonb,
    'active'
),
(
    '01JBP0ORCH0DBSENSOR00001',
    'DatabaseReadinessSensor',
    'Database Readiness Sensor',
    'Runs a polling SQL check until the source or dependency is ready.',
    'ORCHESTRATION',
    '1.0.0',
    '[{"name":"sql","type":"string","required":true},{"name":"connection_id","type":"string","default":"pulse_sql_default"},{"name":"poke_interval_seconds","type":"integer","default":300},{"name":"timeout_seconds","type":"integer","default":3600},{"name":"mode","type":"enum","options":["poke","reschedule"],"default":"reschedule"}]'::jsonb,
    '[]'::jsonb,
    '[{"name":"ready_signal","description":"Proceed when database readiness check passes"}]'::jsonb,
    false,
    false,
    'sensing',
    '["airflow_sensor"]'::jsonb,
    'airflow',
    'orchestration_sensor',
    '["bronze","silver","gold"]'::jsonb,
    '{"phase":"gate4","purpose":"explicit_sensing"}'::jsonb,
    '{"sql":{"type":"string","required":true}}'::jsonb,
    '{"connection_id":{"type":"string"},"poke_interval_seconds":{"type":"integer"},"timeout_seconds":{"type":"integer"},"mode":{"type":"enum"}}'::jsonb,
    '{"editor":"sql_sensor"}'::jsonb,
    'runtime_only',
    false,
    '{"effect_type":"readiness_gate","conflict_policy":"block"}'::jsonb,
    '{"airflow_operator":"sql_sensor"}'::jsonb,
    'active'
),
(
    '01JBP0ORCH0DAGSENSOR0001',
    'DatasetDependencySensor',
    'Dataset Dependency Sensor',
    'Waits for another DAG or task dependency before continuing.',
    'ORCHESTRATION',
    '1.0.0',
    '[{"name":"upstream_dag_id","type":"string","required":true},{"name":"upstream_task_id","type":"string"},{"name":"allowed_states","type":"string[]","default":["success"]},{"name":"poke_interval_seconds","type":"integer","default":300},{"name":"timeout_seconds","type":"integer","default":3600}]'::jsonb,
    '[]'::jsonb,
    '[{"name":"ready_signal","description":"Proceed when upstream dependency is satisfied"}]'::jsonb,
    false,
    false,
    'sensing',
    '["airflow_sensor"]'::jsonb,
    'airflow',
    'orchestration_sensor',
    '["bronze","silver","gold"]'::jsonb,
    '{"phase":"gate4","purpose":"explicit_sensing"}'::jsonb,
    '{"upstream_dag_id":{"type":"string","required":true}}'::jsonb,
    '{"upstream_task_id":{"type":"string"},"allowed_states":{"type":"string[]"},"poke_interval_seconds":{"type":"integer"},"timeout_seconds":{"type":"integer"}}'::jsonb,
    '{"editor":"dependency_sensor"}'::jsonb,
    'runtime_only',
    false,
    '{"effect_type":"dependency_gate","conflict_policy":"block"}'::jsonb,
    '{"airflow_operator":"external_task_sensor"}'::jsonb,
    'active'
),
(
    '01JBP0ORCH0EVENTSENSOR01',
    'ExternalEventSensor',
    'External Event Sensor',
    'Polls an HTTP endpoint or event source until an external trigger is observed.',
    'ORCHESTRATION',
    '1.0.0',
    '[{"name":"event_url","type":"string","required":true},{"name":"success_status_code","type":"integer","default":200},{"name":"poke_interval_seconds","type":"integer","default":300},{"name":"timeout_seconds","type":"integer","default":3600}]'::jsonb,
    '[]'::jsonb,
    '[{"name":"ready_signal","description":"Proceed when external event is observed"}]'::jsonb,
    false,
    false,
    'sensing',
    '["airflow_sensor"]'::jsonb,
    'airflow',
    'orchestration_sensor',
    '["bronze","silver","gold"]'::jsonb,
    '{"phase":"gate4","purpose":"explicit_sensing"}'::jsonb,
    '{"event_url":{"type":"string","required":true}}'::jsonb,
    '{"success_status_code":{"type":"integer"},"poke_interval_seconds":{"type":"integer"},"timeout_seconds":{"type":"integer"}}'::jsonb,
    '{"editor":"event_sensor"}'::jsonb,
    'runtime_only',
    false,
    '{"effect_type":"event_gate","conflict_policy":"block"}'::jsonb,
    '{"airflow_operator":"python_sensor"}'::jsonb,
    'active'
)
ON CONFLICT (blueprint_key) DO NOTHING;
