package com.pulse.broker.model;

public enum BrokerBlockerCode {
    BROKER_TRUST_BINDING_MISSING,
    BROKER_TRUST_BINDING_UNVALIDATED,
    BROKER_CROSS_TENANT_FORBIDDEN,
    BROKER_FACT_SIGNATURE_INVALID,
    BROKER_REQUEST_PATH_BODY_MISMATCH,
    BROKER_PEER_UNREACHABLE,
    BROKER_TARGET_MIRROR_STALE,
    BROKER_REMOTE_TARGET_REF_UNKNOWN,
    BROKER_CANCEL_ACTOR_NOT_ALLOWED;

    public String wire() {
        return name();
    }
}
