apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: pulse-backend
  labels:
    app: pulse-backend
spec:
  source:
    type: Git
    git:
      uri: https://github.com/naghegde13/pulse-test.git
      ref: main
    contextDir: backend
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: pulse-backend:latest
  triggers:
    - type: ConfigChange
    - type: ImageChange
