apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: pulse-backend
  labels:
    app: pulse-backend
spec:
  source:
    type: Git
    git:
      uri: https://github.com/naghegde13/pulse-test.git
      ref: main
    contextDir: backend
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: DockerImage
        name: registry.access.redhat.com/ubi9/openjdk-21:1.24
      incremental: false
  output:
    to:
      kind: ImageStreamTag
      name: pulse-backend:latest
  resources:
    requests:
      cpu: "500m"
      memory: "2Gi"
    limits:
      cpu: "2"
      memory: "4Gi"
  triggers:
    - type: ConfigChange
    - type: ImageChange
