apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: pulse-backend
  labels:
    app: pulse-backend
spec:
  source:
    type: Binary
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: ubi8-openjdk-21:1.18
        namespace: openshift
      scripts: image:///usr/local/s2i
      incremental: true
  output:
    to:
      kind: ImageStreamTag
      name: pulse-backend:latest
  triggers:
    - type: ConfigChange
