apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: pulse-backend
  labels:
    app: pulse-backend
spec:
  runPolicy: SerialLatestOnly
  completionDeadlineSeconds: 2400
  source:
    type: Git
    git:
      uri: https://github.com/naghegde13/pulse-test.git
      ref: main
    contextDir: backend
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: DockerImage
        name: registry.access.redhat.com/ubi9/openjdk-21:1.24
      env:
        - name: GRADLE_OPTS
          value: "-Dorg.gradle.jvmargs=-Xms512m -Xmx2048m -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8 -Dorg.gradle.workers.max=1 -Dorg.gradle.vfs.watch=false"
        - name: JAVA_TOOL_OPTIONS
          value: "-XX:+ExitOnOutOfMemoryError"
      incremental: false
  output:
    to:
      kind: ImageStreamTag
      name: pulse-backend:latest
  resources:
    requests:
      cpu: "1"
      memory: "3Gi"
    limits:
      cpu: "3"
      memory: "6Gi"
  triggers:
    - type: ConfigChange
    - type: ImageChange
