# PULSE codegen example: AnomalyDetection — statistical anomaly detection
# on a silver table using Great Expectations checkpoints.
#
# What this blueprint does (and what it does NOT):
#   - Detects per-column distributional anomalies on the most recent slice
#     (today's partition, or a configurable lookback window).
#   - Uses BOTH parametric (mean within historical band) and non-parametric
#     (z-score on row-level values) checks so the agent doesn't have to
#     pre-decide which is right for the metric.
#   - Does NOT enforce schema, nulls, or referential integrity — that's
#     DQValidator's job (#27 boundary). AnomalyDetection assumes silver
#     has already passed structural validation.
#   - Does NOT block downstream gold builds by default; severity is
#     configurable. WARN logs the anomaly and continues; ERROR raises.
#
# Convention notes:
#   - __PLACEHOLDER__ tokens are substituted by CodeGenerationService at
#     codegen time from SubPipelineInstance.params (the user's blueprint
#     config). They are NOT env vars.
#   - PULSE_* env vars are runtime-only (Airflow per-run templates).
#   - Date inputs (the historical band's [start, end]) are RESOLVED AT
#     RUNTIME by pulse_dates so the band slides with the run date.
#   - Generated by PULSE codegen against the AnomalyDetection blueprint.
#     The agent SHOULD pattern its proposed params and DAG wiring on
#     this file.

from datetime import date
import json
import logging
import os

import great_expectations as gx
from great_expectations.checkpoint import UpdateDataDocsAction
from pyspark.sql import SparkSession
from pyspark.sql import functions as F

from pulse_dates import resolve_mnemonic


# ---------------------------------------------------------------------
# Runtime-only — Airflow per-execution values.
# ---------------------------------------------------------------------
RUN_ID = os.environ["PULSE_RUN_ID"]
PULSE_BUSINESS_DATE = os.environ.get("PULSE_BUSINESS_DATE", date.today().isoformat())
PULSE_PROCESSING_TS = os.environ.get("PULSE_PROCESSING_TS", "{{ ts }}")
AS_OF_DATE = date.fromisoformat(PULSE_BUSINESS_DATE)


# ---------------------------------------------------------------------
# Static config — substituted at codegen time from blueprint params.
# ---------------------------------------------------------------------
PIPELINE_NAME = "__PIPELINE_NAME__"
TENANT_SLUG = "__TENANT_SLUG__"
DOMAIN_SLUG = "__DOMAIN_SLUG__"
SILVER_TABLE = "__SILVER_TABLE__"
# Storage convention (#30) — read-side format-branched.
LAKE_FORMAT = "__LAKE_FORMAT__"
STORAGE_BACKEND = "__STORAGE_BACKEND__"
TABLE_PATH = "__TABLE_PATH__"           # populated for path-based formats
BQ_TABLE = "__BQ_TABLE__"               # populated for bq_native
MONITORED_COLUMN = "__MONITORED_COLUMN__"     # numeric column whose distribution we watch
PARTITION_COLUMN = "__PARTITION_COLUMN__"     # usually 'ds' from medallion convention

# Statistical band — the historical mean/stddev are computed from the
# slice of silver between WINDOW_START and WINDOW_END. Mnemonic-aware so
# a daily run can use BOM-3..EOM-1 to mean "the last 3 completed months".
WINDOW_START_INPUT = "__WINDOW_START_INPUT__"
WINDOW_END_INPUT = "__WINDOW_END_INPUT__"
HOLIDAY_CALENDAR_ID = "__HOLIDAY_CALENDAR_ID__"   # 'US-FED' | 'US-NYSE'
FISCAL_OFFSET_MONTHS = __FISCAL_OFFSET_MONTHS__   # int from domain.business_date_config

# Statistical thresholds.
Z_SCORE_THRESHOLD = __Z_SCORE_THRESHOLD__         # typical: 3.0 (3-sigma)
MEAN_LOWER_BOUND = __MEAN_LOWER_BOUND__           # absolute floor on observed daily mean
MEAN_UPPER_BOUND = __MEAN_UPPER_BOUND__           # absolute ceiling on observed daily mean

# Severity controls whether anomalies block the DAG.
#   "WARN"  → log + write to anomalies report, do NOT raise.
#   "ERROR" → raise after logging, fails the Airflow task.
SEVERITY = "__SEVERITY__"

# GX site — Data Docs are published here; usually a domain-shared bucket.
GX_DOCS_PATH = "__GX_DOCS_PATH__"   # full URI; we split into bucket + prefix below
_split = GX_DOCS_PATH.replace("://", " ").split(" ", 1)
_bucket_split = _split[1].split("/", 1) if len(_split) == 2 else ["", ""]
GX_DOCS_BUCKET = _bucket_split[0]
GX_DOCS_PREFIX = _bucket_split[1] if len(_bucket_split) > 1 else ""


# ---------------------------------------------------------------------
# Resolve historical band against the tenant's holiday calendar.
# ---------------------------------------------------------------------
WINDOW_START = resolve_mnemonic(
    WINDOW_START_INPUT, as_of=AS_OF_DATE,
    calendar_id=HOLIDAY_CALENDAR_ID,
    fiscal_offset_months=FISCAL_OFFSET_MONTHS,
)
WINDOW_END = resolve_mnemonic(
    WINDOW_END_INPUT, as_of=AS_OF_DATE,
    calendar_id=HOLIDAY_CALENDAR_ID,
    fiscal_offset_months=FISCAL_OFFSET_MONTHS,
)


log = logging.getLogger("pulse.anomaly_detection")
log.setLevel(logging.INFO)


def main():
    spark = (
        SparkSession.builder
        .appName(f"pulse-anomaly-{PIPELINE_NAME}-{RUN_ID}")
        .getOrCreate()
    )

    # Format-branched read of the silver table (TABLE_PATH from resolver).
    def _read_silver():
        if LAKE_FORMAT == "delta": return spark.read.format("delta").load(TABLE_PATH)
        if LAKE_FORMAT in ("iceberg_external", "iceberg_bq_managed"):
            return spark.read.format("iceberg").load(TABLE_PATH)
        if LAKE_FORMAT == "parquet": return spark.read.format("parquet").load(TABLE_PATH)
        if LAKE_FORMAT == "bq_native":
            return spark.read.format("bigquery").option("table", BQ_TABLE).load()
        raise ValueError(f"Unsupported LAKE_FORMAT: {LAKE_FORMAT}")
    log.info(
        "AnomalyDetection start. table=%s as_of=%s band=[%s, %s] (from %r..%r) "
        "monitored_col=%s z=%.2f mean_band=[%.4f, %.4f] severity=%s",
        SILVER_TABLE, AS_OF_DATE, WINDOW_START, WINDOW_END,
        WINDOW_START_INPUT, WINDOW_END_INPUT, MONITORED_COLUMN,
        Z_SCORE_THRESHOLD, MEAN_LOWER_BOUND, MEAN_UPPER_BOUND, SEVERITY,
    )

    # --- Fetch only today's partition for the row-level z-score check.
    # Loading the entire table is a frequent footgun on multi-TB silvers.
    today_df = (
        _read_silver()
        .filter(F.col(PARTITION_COLUMN) == AS_OF_DATE.isoformat())
    )
    today_count = today_df.count()
    if today_count == 0:
        log.warning("No rows for %s on %s — skipping anomaly check (no signal).",
                    SILVER_TABLE, AS_OF_DATE)
        spark.stop()
        return

    # --- Compute the historical band's daily mean once, in-engine.
    band_df = (
        _read_silver()
        .filter(F.col(PARTITION_COLUMN) >= WINDOW_START.isoformat())
        .filter(F.col(PARTITION_COLUMN) <= WINDOW_END.isoformat())
        .groupBy(PARTITION_COLUMN)
        .agg(F.mean(MONITORED_COLUMN).alias("daily_mean"))
    )
    band_stats = band_df.agg(
        F.mean("daily_mean").alias("band_mean"),
        F.stddev("daily_mean").alias("band_stddev"),
    ).first()
    log.info("historical band: mean=%.6f stddev=%.6f n_days=%d",
             band_stats["band_mean"] or 0.0, band_stats["band_stddev"] or 0.0,
             band_df.count())

    # --- Run GX checkpoint on today's slice.
    context = gx.get_context(mode="ephemeral")
    context.add_data_docs_site(
        site_name="pulse_docs",
        site_config={
            "class_name": "SiteBuilder",
            "store_backend": {"class_name": "TupleS3StoreBackend",
                              "bucket": GX_DOCS_BUCKET,
                              "prefix": GX_DOCS_PREFIX},
            "site_index_builder": {"class_name": "DefaultSiteIndexBuilder"},
        },
    )
    ds = context.data_sources.add_spark(name="pulse_spark")
    asset = ds.add_dataframe_asset(name=f"{SILVER_TABLE}_today")
    batch = asset.add_batch_definition_whole_dataframe(
        name=f"{SILVER_TABLE}_{AS_OF_DATE.isoformat()}",
    )

    suite = gx.ExpectationSuite(name=f"{SILVER_TABLE}_anomaly_{AS_OF_DATE.isoformat()}")
    # Row-level: each row's MONITORED_COLUMN within Z_SCORE_THRESHOLD sigmas.
    suite.add_expectation(gx.expectations.ExpectColumnValueZScoresToBeLessThan(
        column=MONITORED_COLUMN, threshold=Z_SCORE_THRESHOLD, double_sided=True,
    ))
    # Aggregate-level: today's mean within the absolute business band.
    suite.add_expectation(gx.expectations.ExpectColumnMeanToBeBetween(
        column=MONITORED_COLUMN,
        min_value=MEAN_LOWER_BOUND, max_value=MEAN_UPPER_BOUND,
    ))
    suite = context.suites.add(suite)

    val_def = context.validation_definitions.add(
        gx.ValidationDefinition(
            name=f"{SILVER_TABLE}_anomaly_val",
            data=batch, suite=suite,
        )
    )
    checkpoint = context.checkpoints.add(
        gx.Checkpoint(
            name=f"{SILVER_TABLE}_anomaly_checkpoint",
            validation_definitions=[val_def],
            actions=[UpdateDataDocsAction(name="update_docs")],
        )
    )
    result = checkpoint.run(batch_parameters={"dataframe": today_df})

    summary = {
        "pipeline": PIPELINE_NAME,
        "run_id": RUN_ID,
        "table": SILVER_TABLE,
        "as_of": AS_OF_DATE.isoformat(),
        "today_rows": today_count,
        "band_start": WINDOW_START.isoformat(),
        "band_end": WINDOW_END.isoformat(),
        "band_mean": band_stats["band_mean"],
        "band_stddev": band_stats["band_stddev"],
        "success": result.success,
        "statistics": result.statistics,
    }
    log.info("anomaly result: %s", json.dumps(summary, default=str))

    if not result.success:
        if SEVERITY == "ERROR":
            spark.stop()
            raise RuntimeError(
                f"AnomalyDetection failed for {SILVER_TABLE} on {AS_OF_DATE}: "
                f"{result.statistics}"
            )
        log.warning("AnomalyDetection WARN-level failure on %s — DAG continues.",
                    SILVER_TABLE)

    spark.stop()


if __name__ == "__main__":
    main()
